name: Update and Publish Firebase Remote Config

on:
  push:
    branches:
      - main

jobs:
  update_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file token/pom.xml

      - name: Store artifact
        run: |
          mkdir -p artifacts
          cp token/target/*.jar artifacts/
      - name: Commit and push artifact
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add artifacts/
          git commit -m "Add built artifact"
          git push origin HEAD:refs/heads/main

      - name: Execute Java Program
        run: java -cp artifacts/*.jar com.google.firebase.samples.config.Configure

      # Add additional steps here if needed
